# sonar setup
soundspeed: 1500
sonar_ip: "192.168.1.45"
start_range: 1
stop_range: 20
data_full_path: "/root/Documents/bvtsdk/data/20m.son"
SDK_path: "/root/Documents/bvtsdk/"
record_enable: 0





